
name: PyPI deploy

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  pypi-deploy:
    name: Deploying Python Package
    runs-on: ubuntu-20.04
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v2
      name: Install Python

    - name: Build source distribution
      run: |
        pipx run build --sdist

    - uses: pypa/gh-action-pypi-publish@v1.8.11
